[package]
name = "klondike-cli"

edition.workspace = true
version.workspace = true

[[bin]]
name = "klondike-cli"
path = "main.rs"

[dependencies]
anyhow = "1.0.71"
card.workspace = true
klondike.workspace = true
rand = "0.8.5"
rand_xoshiro = "0.6.0"
