[package]
name = "enum-trait-derive"

edition.workspace = true
version.workspace = true

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.59"
quote = "1.0.28"
syn = "2.0.18"
